name: lcv-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6
  - anaconda
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - statsmodels
  - pandas
  - nipype>=1.1.1
  - pyopengl
  - pillow
  - lxml
  - openpyxl
  - xlrd
  - configobj
  - pyyaml
  - gevent
  - msgpack-python
  - psutil
  - pytables
  - requests[security]
  - cffi
  - wxpython
  - cython
  - pyzmq
  - pyserial
  - pysoundfile
  - python-bidi
  - moviepy
  - pyosf
  - osfclient
  - h5py
  - nibabel
  - scikit-learn
  - scikit-image
  - greenlet==0.4.15
  - pip:
      - pyglet
      - neuropythy
      - zmq
      - json-tricks
      - pyparallel
      - sounddevice
      - pygame
      - pysoundcard
      - psychopy_ext
      - psychopy
      - pydeface

