name: lcv-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6
  - anaconda
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - scikit-learn>=0.22
  - scikit-image
  - seaborn
  - statsmodels
  - pandas

